using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Faction.Windows;

[GenerateTypedNameReferences]
public sealed partial class FactionWindow : DefaultWindow
{
    public FactionWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

