- type: job
  id: BlugoslaviaCaptain
  name: job-name-civ-blugoslavia-cpt
  faction: Blugoslavia
  originalName: Captain
  description: job-description-civ-blugoslavia-cpt
  playTimeTracker: JobBlugoslaviaCaptain
  requirements:
    - !type:TotalJobsTimeRequirement
      group: CivJobsSquadLeader
      time: 7200 # 2 hours
  startingGear: BlugoslaviaCaptainGear
  icon: "JobIconICpt"
  supervisors: job-supervisors-nobody
  ranks:
    RankMajor:
      - !type:RoleTimeRequirement
        role: JobBlugoslaviaCaptain
        time: 18000 # 5 hours
    RankCaptain: []
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - Blugoslavia
        - type: ShowFactionIcons
          factionIcon: SovietFaction
          jobIcon: JobIconICpt
          assignSquad: false

- type: startingGear
  id: BlugoslaviaCaptainGear
  equipment:
    shoes: civ13_shoes_Soviet_sapogi_boots
    jumpsuit: civ13_uniform_Soviet_officer_uniform
    outerClothing: civ13_suit_Soviet_officer_coat
    neck: civ13_accessory_N34_B_body_armor
    belt: civ13_pistol_Makarov_PM
    pocket2: civ13_magazine_PM_Makarov_magazine_(9x18mm)
    head: civ13_head_soviet_officer_cap
    pocket1: Compass
    ears: ClothingHeadsetBlugoslavia

# Sergeant

- type: job
  id: BlugoslaviaSergeant
  originalName: Sergeant
  name: job-name-civ-blugoslavia-sgt
  faction: Blugoslavia
  description: job-description-civ-blugoslavia-sgt
  playTimeTracker: JobBlugoslaviaSergeant
  requirements:
    - !type:TotalJobsTimeRequirement
      group: CivJobsEnlisted
      time: 7200 # 2 hours
  startingGear: BlugoslaviaSergeantGear
  icon: "JobIconISgt"
  supervisors: job-supervisors-cpt
  ranks:
    RankSergeantMajor:
      - !type:RoleTimeRequirement
        role: JobBlugoslaviaSergeant
        time: 36000 # 10 hours
    RankStaffSergeant:
      - !type:RoleTimeRequirement
        role: JobBlugoslaviaSergeant
        time: 10800 # 3 hours
    RankSergeant: []
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - Blugoslavia
        - type: ShowFactionIcons
          factionIcon: SovietFaction
          jobIcon: JobIconISgt
          assignSquad: true

- type: startingGear
  id: BlugoslaviaSergeantGear
  equipment:
    shoes: civ13_shoes_leather_shoes_1
    jumpsuit: civ13_uniform_Soviet_uniform
    neck: civ13_accessory_N34_B_body_armor
    head: civ13_head_soviet_pilotka
    belt: civ13_pistol_Makarov_PM
    pocket1: civ13_magazine_PM_Makarov_magazine_(9x18mm)
    pocket2: Compass
    ears: ClothingHeadsetBlugoslavia
  inhand:
    - civ13_ar_AK_12

# Assault Rifleman

- type: job
  id: BlugoslaviaRifleman
  name: job-name-civ-blugoslavia-rifleman
  faction: Blugoslavia
  originalName: Rifleman
  description: job-description-civ-blugoslavia-rifleman
  playTimeTracker: JobBlugoslaviaRifleman
  startingGear: BlugoslaviaRiflemanGear
  randomStartingGears: [BlugoslaviaRiflemanGear, BlugoslaviaRiflemanGear2]
  icon: "JobIconICpl"
  supervisors: job-supervisors-cpt
  ranks:
    RankLanceCorporal:
      - !type:RoleTimeRequirement
        role: JobBlugoslaviaRifleman
        time: 36000 # 10 hours
    RankPrivateFirstClass:
      - !type:RoleTimeRequirement
        role: JobBlugoslaviaRifleman
        time: 10800 # 3 hours
    RankPrivate: []
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - Blugoslavia
        - type: ShowFactionIcons
          factionIcon: SovietFaction
          jobIcon: JobIconRifleman
          assignSquad: true

- type: startingGear
  id: BlugoslaviaRiflemanGear
  equipment:
    shoes: civ13_shoes_Soviet_sapogi_boots
    jumpsuit: civ13_uniform_Soviet_uniform
    neck: civ13_accessory_N34_B_body_armor
    head: civ13_head_soviet_helmet
    belt: ClothingWebbingSovietCWRifleman
    pocket1: FlashlightLanternMilitary
    pocket2: Gauze
    ears: ClothingHeadsetBlugoslavia
  inhand:
    - civ13_ar_AK_12

- type: startingGear
  id: BlugoslaviaRiflemanGear2
  equipment:
    shoes: civ13_shoes_Soviet_sapogi_boots
    jumpsuit: civ13_uniform_Soviet_amoeba_outfit
    gloves: ClothingHandsGlovesFingerless
    belt: ClothingWebbingSovietCWRifleman
    neck: civ13_accessory_N34_B_body_armor
    head: civ13_head_soviet_helmet
    pocket1: FlashlightLanternMilitary
    pocket2: Gauze
    ears: ClothingHeadsetBlugoslavia
  inhand:
    - civ13_ar_AK_12

# Machinegunner

- type: job
  id: BlugoslaviaMachinegunner
  name: job-name-civ-blugoslavia-machinegunner
  faction: Blugoslavia
  originalName: Machinegunner
  description: job-description-civ-blugoslavia-machinegunner
  playTimeTracker: JobBlugoslaviaMachinegunner
  startingGear: BlugoslaviaMachinegunnerGear
  randomStartingGears: [BlugoslaviaMachinegunnerGear, BlugoslaviaMachinegunnerGear2]
  icon: "JobIconMg"
  supervisors: job-supervisors-cpt
  requirements:
    - !type:TotalJobsTimeRequirement
      group: CivJobsEnlisted
      time: 3600 # 1 hours
  ranks:
    RankLanceCorporal:
      - !type:RoleTimeRequirement
        role: JobBlugoslaviaMachinegunner
        time: 36000 # 10 hours
    RankPrivateFirstClass:
      - !type:RoleTimeRequirement
        role: JobBlugoslaviaMachinegunner
        time: 10800 # 3 hours
    RankPrivate: []
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - Blugoslavia
        - type: ShowFactionIcons
          factionIcon: SovietFaction
          jobIcon: JobIconMg
          assignSquad: true

- type: startingGear
  id: BlugoslaviaMachinegunnerGear
  equipment:
    shoes: civ13_shoes_Soviet_sapogi_boots
    jumpsuit: civ13_uniform_Soviet_uniform
    gloves: ClothingHandsGlovesFingerless
    belt: ClothingWebbingSovietCWMG
    neck: civ13_accessory_N34_B_body_armor
    head: civ13_head_soviet_helmet
    pocket1: CombatKnife
    pocket2: Gauze
    ears: ClothingHeadsetBlugoslavia
  inhand:
    - civ13_mg_RPD_machine_gun

- type: startingGear
  id: BlugoslaviaMachinegunnerGear2
  equipment:
    shoes: civ13_shoes_Soviet_sapogi_boots
    jumpsuit: civ13_uniform_Soviet_amoeba_outfit
    gloves: ClothingHandsGlovesFingerless
    belt: ClothingWebbingSovietCWMG
    neck: civ13_accessory_N34_B_body_armor
    head: civ13_head_soviet_ushanka_1
    pocket1: CombatKnife
    pocket2: Gauze
    ears: ClothingHeadsetBlugoslavia
  inhand:
    - civ13_mg_RPD_machine_gun

# Medic

- type: job
  id: BlugoslaviaMedic
  name: job-name-civ-blugoslavia-medic
  faction: Blugoslavia
  originalName: Medic
  description: job-description-civ-blugoslavia-medic
  playTimeTracker: JobBlugoslaviaMedic
  startingGear: BlugoslaviaMedicGear
  icon: "JobIconMedic"
  supervisors: job-supervisors-cpt
  requirements:
    - !type:TotalJobsTimeRequirement
      group: CivJobsEnlisted
      # time: 9000 # 2.5 hours
      time: 3600 # 1 hour temporarily until people build up playtime
  ranks:
    RankSergeant:
      - !type:RoleTimeRequirement
        role: JobBlugoslaviaMedic
        time: 10800 # 3 hours
    RankCorporal: []
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - Blugoslavia
        - type: ShowFactionIcons
          factionIcon: SovietFaction
          jobIcon: JobIconMedic
          assignSquad: false

- type: startingGear
  id: BlugoslaviaMedicGear
  equipment:
    shoes: civ13_shoes_Soviet_sapogi_boots
    jumpsuit: civ13_uniform_Soviet_uniform
    neck: civ13_accessory_N34_B_body_armor
    head: civ13_head_soviet_medical_helmet
    belt: ClothingSatchelMedicalMedsFilled
    back: ClothingBackpackDuffelFilled
    pocket1: FlashlightLanternMilitary
    pocket2: civ13_magazine_AK_74_magazine_(5.45x39mm)
    ears: ClothingHeadsetBlugoslavia
  inhand:
    - civ13_ar_AK_12
