- type: entity
  id: BaseMindRole
  name: Mind Role
  description: Mind Role entity
  abstract: true
  components:
    - type: MindRole

- type: entity
  parent: BaseMindRole
  id: BaseMindRoleAntag
  abstract: true
  components:
    - type: MindRole
      antag: true
      antagPrototype: GenericAntagonist
      roleType: SoloAntagonist

#Observer
- type: entity
  parent: BaseMindRole
  id: MindRoleObserver
  name: Observer Role
  components:
    - type: ObserverRole

#Ghost Roles
- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleNeutral
  name: Ghost Role
  components:
    - type: GhostRoleMarkerRole

- type: entity
  parent: MindRoleGhostRoleNeutral
  id: MindRoleGhostRoleFamiliar
  name: Ghost Role (Familiar)
  components:
    - type: MindRole
      roleType: Familiar

- type: entity
  parent: [BaseMindRoleAntag, MindRoleGhostRoleNeutral]
  id: MindRoleGhostRoleFreeAgent
  name: Ghost Role (Free Agent)
  components:
    - type: MindRole
      roleType: FreeAgent
      antagPrototype: GenericFreeAgent

- type: entity
  parent: MindRoleGhostRoleNeutral
  id: MindRoleGhostRoleFreeAgentHarmless
  name: Ghost Role (Free Agent)
  components:
    - type: MindRole
      roleType: FreeAgent

- type: entity
  parent: MindRoleGhostRoleNeutral
  id: MindRoleGhostRoleSilicon
  name: Ghost Role (Silicon)
  components:
    - type: MindRole
      roleType: Silicon

- type: entity
  parent: [BaseMindRoleAntag, MindRoleGhostRoleNeutral]
  id: MindRoleGhostRoleSiliconAntagonist
  name: Ghost Role (Silicon Antagonist)
  components:
    - type: MindRole
      roleType: SiliconAntagonist
      antagPrototype: GenericSiliconAntagonist

- type: entity
  parent: [BaseMindRoleAntag, MindRoleGhostRoleNeutral]
  id: MindRoleGhostRoleSoloAntagonist
  name: Ghost Role (Solo Antagonist)

- type: entity
  parent: [BaseMindRoleAntag, MindRoleGhostRoleNeutral]
  id: MindRoleGhostRoleTeamAntagonist
  name: Ghost Role (Team Antagonist)
  components:
    - type: MindRole
      roleType: TeamAntagonist
      antagPrototype: GenericTeamAntagonist

# This should be used (or inherited) for team antags that are summoned or converted in large quantities, and are "secondary" to other antags
# TODO: sort weight
- type: entity
  parent: MindRoleGhostRoleTeamAntagonist
  id: MindRoleGhostRoleTeamAntagonistFlock
  name: Ghost Role (Team Antagonist)

# The Job MindRole holds the mob's Job prototype
- type: entity
  parent: BaseMindRole
  id: MindRoleJob
  name: Job Role
  # JobPrototype is filled by SharedJobSystem
