name: Compile and Update Target Repo

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  compile-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y python3-paramiko python3-lxml

      - uses: actions/checkout@v3.6.0
        with:
          submodules: "recursive"
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 9.0.x

      - name: Setup Submodule
        run: |
          git submodule update --init --recursive
      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5

      - name: Update Engine Submodules
        run: |
          cd RobustToolbox/
          git submodule update --init --recursive

      - name: Install dependencies
        run: dotnet restore

      # Run your compilation script
      - name: Package Client
        run: dotnet build --configuration Release

      # Checkout the target repository
      - name: Checkout Target Repo
        uses: actions/checkout@v4
        with:
          repository: taislin/civ14_compiled_client
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          path: target-repo # Clone into a subdirectory

      # Copy compiled output to target repo
      - name: Update Target Repo
        run: | # Copy files from source-repo/output to target repo, preserving timestamps
          export DISPLAY=:0
          rsync -av --ignore-existing target-repo/ . || true
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          if git status --porcelain | grep .; then
            git commit -m "Update from source repo compilation - changed files only"
            git push
          else
            echo "No changes detected, skipping commit and push"
          fi
